### ISSUE TITLE
[CSS] Add scroll bar when step output is too long

### ISSUE THREAD

**Issue by taoufix** [alvins82/java-mini-profiler-core#2]
When there is an overflow of SQL requests for example, the Step <li> doesn't handle show scrollbars.

As a workaround I'm using the stylish extensions with this style:

``` css
ul#mp-req-profile-0-d {
  max-height: 500px !important;
  overflow: auto !important;
}
```
